---
title: "Mortality Rate Visualizations"
author: "Susan Chen, Emily Hou, Cassandra Tai, Vicki Truong, Richard Yim"
date: "5/14/2020"
output: html_document
---
Mortality Rate Overall
```{r}
library(dplyr)
library(ggplot2)
global = read.csv("covidData_clean.csv")
global = global %>% mutate(rate = 100 * total_deaths / total_cases) #create column for mortality rate
global$rate[is.na(global$rate)]<-0
origin <- as.Date("2019-12-31")
global = global %>% mutate(days_since = as.Date(date) - origin) #create column for days since 12/31/2019, the start of our data overall
narrowed = global %>% filter(location == "World" | iso_code == "USA")
narrowed_march = narrowed %>% mutate(date_2 = as.POSIXct(date)) %>% filter(date_2 > as.POSIXct("2020-03-20")) 
narrowed_march = narrowed_march %>% mutate(days_since = as.Date(date) - as.Date("2020-03-21"))
#as.Date("2020-03-11") - as.Date("2019-12-31") returns 71 days, which is the time between the start of the data and when the WHO declared COVID-19 a global pandemic
g1 = ggplot(data = narrowed, aes(x = days_since, y = rate)) + 
  geom_line(aes(color = location)) + 
  expand_limits(x = c(0,150),y = c(0, 10)) +
  scale_x_continuous(breaks = c(0, 25, 50, 75, 100, 125, 150), expand = c(0,0.01)) + 
  scale_y_continuous(breaks = c(1:10), expand = c(0,.01)) + 
  annotate("segment", x = 71, xend = 71, y = 0, yend = 8) + geom_point(aes(x = 71, y = 8)) + 
  annotate("text", x = 71, y = 8.75, label = "WHO Declares \nCOVID-19 a \nGlobal Pandemic", size = 2.5) + 
  labs(title = "Mortality Rate Over Time",x="Days Since 12/31/2019", y = "Mortality Rate (Percentage)") + 
  theme_light()
g1
```

Daily New Cases
```{r}
g2 = ggplot(data = narrowed, aes(x = days_since, y = new_cases)) + 
  geom_line(aes(color = location)) + 
  expand_limits(x = c(0,150),y = c(0, 110000)) +
  scale_x_continuous(breaks = c(0, 25, 50, 75, 100, 125, 150), expand = c(0,0.01)) + 
  scale_y_continuous(breaks = c(10^4,2*10^4,3*10^4,4*10^4,5*10^4,6*10^4,7*10^4,8*10^4,9*10^4,10*10^4,11*10^4), expand = c(0,0.1)) + 
  annotate("segment", x = 71, xend = 71, y = 0, yend = 90000) + geom_point(aes(x = 71, y = 90000)) + 
  annotate("text", x = 71, y = 100000, label = "WHO Declares \nCOVID-19 a \nGlobal Pandemic", size = 2.5) + 
  labs(title = "New Cases Over Time",x="Days Since 12/31/2019", y = "New Cases") + 
  theme_light()
g2
```

Total Cases Over Time
```{r}
g3 = ggplot(data = narrowed, aes(x = days_since, y = total_cases)) + 
  geom_line(aes(color = location)) + 
  expand_limits(x = c(0,150),y = c(0, 1000000)) +
  scale_x_continuous(breaks = c(0, 25, 50, 75, 100, 125, 150), expand = c(0,0.01)) + 
  scale_y_continuous(breaks = c(10^6,2*10^6,3*10^6,4*10^6,5*10^6), expand = c(0,0.1)) + 
  annotate("segment", x = 71, xend = 71, y = 0, yend = 3500000) + geom_point(aes(x = 71, y = 3500000)) + 
  annotate("text", x = 71, y = 3800000, label = "WHO Declares \nCOVID-19 a \nGlobal Pandemic", size = 2.5) + 
  labs(title = "Total Cases Over Time",x="Days Since 12/31/2019", y = "Total Cases") + 
  theme_light()
g3
```

Mortality Rate w/ Date starting at 03/21
```{r}
g4 = ggplot(data = narrowed_march, aes(x = days_since, y = rate)) + 
  geom_line(aes(color = location)) + 
  expand_limits(x = c(0,55),y = c(0, 10)) +
  scale_x_continuous(breaks = seq(0,55,by=5), expand = c(0,0.01)) + 
  scale_y_continuous(breaks = c(1:10), expand = c(0,.01)) + 
  annotate("segment", x = 38, xend = 38, y = 0, yend = 8) + geom_point(aes(x = 38, y = 8)) + 
  annotate("text", x = 37.5, y = 8.75, label = "U.S. Reaches\nOne Million Total Cases\nof COVID-19", size = 2.5) + 
  annotate("segment", x = 12, xend = 12, y = 0, yend = 6) + geom_point(aes(x = 12, y = 6)) + 
  annotate("text", x = 12, y = 7, label = "World Reaches\nOne Million Total Cases\nof COVID-19", size = 2.5) +
  labs(title = "Mortality Rate Over Time",x="Days Since 03/21/2020", y = "Mortality Rate (Percentage)") + 
  theme_light()
g4
```

Daily New Cases w/ Date starting at 03/21
```{r}
g5 = ggplot(data = narrowed_march, aes(x = days_since, y = new_cases)) + 
  geom_line(aes(color = location)) + 
  expand_limits(x = c(0,55),y = c(0, 125000)) +
  scale_x_continuous(breaks = seq(0,55,by=5), expand = c(0,0.01)) + 
  scale_y_continuous(breaks = c(10^4,2*10^4,3*10^4,4*10^4,5*10^4,6*10^4,7*10^4,8*10^4,9*10^4,10*10^4,11*10^4), expand = c(0,0.1)) + 
  annotate("segment", x = 38, xend = 38, y = 0, yend = 105000) + geom_point(aes(x = 38, y = 105000)) + 
  annotate("text", x = 37.5, y = 115000, label = "U.S. Reaches\nOne Million Total Cases\nof COVID-19", size = 2.5) + 
  annotate("segment", x = 12, xend = 12, y = 0, yend = 90000) + geom_point(aes(x = 12, y = 90000)) + 
  annotate("text", x = 12, y = 100000, label = "World Reaches\nOne Million Total Cases\nof COVID-19", size = 2.5) + 
  labs(title = "New Cases Over Time",x="Days Since 03/21/2020", y = "New Cases") + 
  theme_light()
g5
```

Total Cases w/ Date starting at 03/21
```{r}
g6 = ggplot(data = narrowed_march, aes(x = days_since, y = total_cases)) + 
  geom_line(aes(color = location)) + 
  expand_limits(x = c(0,55),y = c(0, 1000000)) +
  scale_x_continuous(breaks = seq(0,55,by=5), expand = c(0,0.01)) + 
  scale_y_continuous(breaks = c(10^6,2*10^6,3*10^6,4*10^6,5*10^6), expand = c(0,0.1)) + 
  annotate("segment", x = 38, xend = 38, y = 0, yend = 3500000) + geom_point(aes(x = 38, y = 3500000)) + 
  annotate("text", x = 37.5, y = 3800000, label = "U.S. Reaches\nOne Million Total Cases\nof COVID-19", size = 2.5) + annotate("segment", x = 12, xend = 12, y = 0, yend = 2000000) + geom_point(aes(x = 12, y = 2000000)) + 
  annotate("text", x = 12, y = 2300000, label = "World Reaches\nOne Million Total Cases\nof COVID-19", size = 2.5) + 
  labs(title = "Total Cases Over Time",x="Days Since 03/21/2020", y = "Total Cases") + 
  theme_light()
g6
```
