---
title: "COVID-19 Sentiment Analysis"
author: "Cassandra, Susan, Vicki, Emily and Richard"
date: "5/13/2020"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Reading in Cleaned Data and Basic Reformatting
```{r}
headlines <- read.csv("data/news_clean.csv")

# Names of variables
names(headlines)

# Load all of the data into the working environment
attach(headlines)
# We ignore the id, timestamp and source, and focus on the title, description and date
headlines <- data.frame(title, description, date)
# Reformat and separate year month and day
headlines$month = substr(date, 6, 7)
headlines$day <- substr(date, 9, 10)
attach(headlines)
```
We want to check how many days there are in the dataset:
```{R}
begin <- headlines$date[1]
end <- headlines$date[length(headlines$date)]
days <- as.Date(end) - as.Date(begin)
days
cat(begin, end)
```

## Frequency of Strings
```{r}
library("ggplot2") #beautiful plots
library("reshape2") #melt-function

plot_word_in_day <- function(phrase){
  freq <- NULL
  days <- unique(headlines$date)
    for(day in days)
    {
      matching_day <- headlines$title[headlines$date == day]
      freq[length(freq)+1] <- sum(grepl(phrase, matching_day, ignore.case = FALSE))
    }
  return(freq)
}

# list <- c("recession", "shutdown", "cure", "vaccine")
list <- c("stay-at-home", "order", "social distancing", "case")
time <- data.frame(seq(as.Date("2020-03-21"),by="day",length.out=53))

# turn off warnings temporarily
options(warn=-1)
for(i in list)
{
  val <- plot_word_in_day(i)
  time <- cbind(time, val)
}
options(warn = 0)

colnames(time) <- c("date", list)
charts <- melt(time, id="date")
names(charts) <- c('x', 'func', 'value')

g=ggplot() +
  geom_line(data = charts, aes(x = x, y = value, color = func),size=1) +
  xlab("year") +
  ylab("frequency")
g+scale_color_manual(values=c("#FF0000", "#FF00D0","#0007FF","#09FF00"))
```

## Sentiment Analysis
```{r}
library(dplyr)
library(tidytext)
library(ggplot2)
library(lubridate) # month and year function
library(data.table) # for the inner join
pos_neg <- get_sentiments("afinn")
pos_neg$X1 <- factor(pos_neg$word)
pos_neg$word <- NULL
pos_neg <- data.frame(pos_neg)
result <- data.frame(matrix(ncol = 2, nrow = 0))
days <- unique(headlines$date)
scoreOverall <- NULL
scoreAverage <- NULL
options(warn=-1)
for(day in days){
  # select words in day
  words_in_day <- data.frame(headlines$title[headlines$date == day])
  # split words 
  h <- apply(words_in_day, MARGIN=1, function(x) strsplit(as.character(x)," "))
  X1 <- unlist(unlist(h, recursive = F))
  xtab <- data.frame(X1)
  #print(dim(xtab))
  #print(dim(pos_neg))
  h2 <- left_join(xtab, pos_neg, by = "X1")
  h2[is.na(h2)] <- 0
  scoreOverall[length(scoreOverall) + 1] <- sum(h2[,2])
  scoreAverage[length(scoreAverage) + 1] <- sum(h2[,2])/sum(h2[,2] != 0)
}
options(warn=0)
scores <- data.frame(cbind(days, scoreOverall, scoreAverage))
#graph Average sentiment
g1=ggplot(data = scores, aes(x = days-1, y = scoreAverage)) +
 geom_line(aes(y = scoreAverage), color = "blue") + 
 labs(title = "Average Sentiment each day", x = "Days since 3/21/2020", y = "Average Sentiment")+ 
  annotate("segment", x = 38, xend = 38, y = 0, yend = -0.6) + geom_point(aes(x = 38, y = -0.6)) + 
  annotate("text", x = 38, y = -.65, label = "U.S. Reaches\nOne Million Total Cases\nof COVID-19", size = 2.5)+ 
  annotate("segment", x = 12, xend = 12, y = 0, yend = -0.6) + geom_point(aes(x = 12, y = -0.6)) + 
  annotate("text", x = 12.5, y = -.68, label = "World Reaches\nOne Million Total Cases\nof COVID-19", size = 2.5)

#graph Overall Sentiment
g2=ggplot(data = scores, aes(x = days-1, y = scoreOverall)) +
 geom_line(aes(y = scoreOverall), color = "red") + 
 labs(title = "Aggregate Sentiment each day", x = "Days since 3/21/2020", y = "Overall Sentiment")+ 
  annotate("segment", x = 38, xend = 38, y = 0, yend = -250) + geom_point(aes(x = 38, y = -250)) + 
  annotate("text", x = 38, y = -268, label = "U.S. Reaches\nOne Million Total Cases\nof COVID-19", size = 2.5)+ 
  annotate("segment", x = 12, xend = 12, y = 0, yend = -250) + geom_point(aes(x = 12, y = -250)) + 
  annotate("text", x = 14, y = -268, label = "World Reaches\nOne Million Total Cases\nof COVID-19", size = 2.5)
g1
g2
```
## Looking at the Data
We have a time-series on the sentiment from coronavirus related news.
```{R}
sent
```
